project/blueprints/articles_blueprint.py
from flask import Blueprint, request, render_template, url_for, session
from werkzeug.utils import redirect

from project import db
from project.blueprints.auth_blueprint import admin_required
from project.model.article import Article
from project.model.reaction import Reaction

article_blueprint = Blueprint('article', __name__)


@article_blueprint.route('/article/all', methods=['GET'])
@admin_required
def list_all():
    return render_template('articles/management.html', articles=Article.find_all())


@article_blueprint.route('/article/<article_id>', methods=['GET'])
def details(article_id):
    article = Article.find_one({'id': article_id})
    # Retrieve and aggregate reactions
    counter_reactions = article.get_reactions()
    # Find user reaction
    reaction = Reaction.find_one({'user_id': session.get('user_id'), 'article_id': article_id})
    user_reaction = reaction.emotion.name if reaction is not None else None
    # Pre-process article's tags
    tags = article.get_tags()
    return render_template('articles/details.html',
                           id=article_id,
                           title=article.title,
                           subtitle=article.subtitle,
                           body=article.body,
                           creation_date=article.creation_date,
                           reactions=counter_reactions,
                           user_reaction=user_reaction,
                           comments=article.comments,
                           tags=tags)


@article_blueprint.route('/article/<article_id>', methods=['DELETE'])
@admin_required
def delete(article_id):
    article = Article.find_one({'id': article_id})
    article.soft_delete()
    db.session.commit()
    return '', 204


@article_blueprint.route('/article/<article_id>/restore', methods=['PATCH'])
@admin_required
def restore(article_id):
    article = Article.find_one({'id': article_id})
    article.restore()
    db.session.commit()
    return '', 200


@article_blueprint.route('/article/<article_id>/edit', methods=['GET', 'POST'])
@admin_required
def edit(article_id):
    article = Article.find_one({'id': article_id})
    if request.method == 'GET':
        tags = article.get_attached_tags()
        return render_template('articles/form.html',
                               title=article.title,
                               article_title=article.title,
                               article_subtitle=article.subtitle,
                               article_body=article.body,
                               is_publish=article.is_publish,
                               header_form='edit article',
                               submit_button='edit',
                               tags=tags)
    elif request.method == 'POST':
        article.title = request.form.get("article_title")
        article.subtitle = request.form.get("article_subtitle")
        article.body = request.form.get("article_body")
        tags = request.form.get("tags")
        article.is_publish = True if request.form.get("article_publish") is not None else False
        article.update()
        article.attach_tags(tags)
        db.session.commit()
        return redirect(url_for('article.details', article_id=article.id))


@article_blueprint.route('/article', methods=['GET', 'POST'])
@admin_required
def create():
    if request.method == 'GET':
        return render_template('articles/form.html', title='create article', header_form='create article', submit_button='create')
    elif request.method == 'POST':
        title = request.form.get("article_title")
        subtitle = request.form.get("article_subtitle")
        body = request.form.get("article_body")
        tags = request.form.get("tags")
        is_publish = True if request.form.get("article_publish") is not None else False
        article = Article(title=title, subtitle=subtitle, body=body, is_publish=is_publish, writer=session.get('user_id'))
        article.create()
        article.attach_tags(tags)
        db.session.commit()
        return redirect(url_for('article.details', article_id=article.id))


@article_blueprint.route('/article/search', methods=['GET'])
def search():
    filters = dict()
    q = request.args.get('q')
    writer = request.args.get('writer')
    if q is not None:
        filters['q'] = q
    if writer is not None:
        filters['writer'] = writer
    filters['is_publish'] = True
    articles = Article.find_all(filters)
    return render_template('articles/search.html', filters=filters, articles=articles)

project/blueprints/auth_blueprint.py
import functools

from flask import Blueprint, request, render_template, session, url_for, flash
from werkzeug.utils import redirect

from project.model.user import User

auth_blueprint = Blueprint('auth', __name__)


# --------------------------------
# Decorators for user control
# --------------------------------
def only_anonymous(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        if session.get('logged_in') is None:
            return fn(*args, **kwargs)
        return redirect(url_for('home.list_publish_articles'))
    return inner


def login_required(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        if session.get('logged_in'):
            return fn(*args, **kwargs)
        return redirect(url_for('home.list_publish_articles', next=request.path))
    return inner


def admin_required(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        if session.get('is_admin'):
            return fn(*args, **kwargs)
        return redirect(url_for('home.list_publish_articles'))
    return inner

# --------------------------------
# Auth blueprints
# --------------------------------
@auth_blueprint.route('/login', methods=['GET', 'POST'])
@only_anonymous
def login():
    next_url = request.args.get('next') or request.form.get('next')
    if request.method == 'POST' and request.form.get('email') and request.form.get('password'):
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.find_one({'email': email, 'enabled': True})
        if user is not None and user.verify_password(password):
            session['logged_in'] = True
            session['user_id'] = user.id
            session['user_name'] = user.first_name
            session.permanent = True    # TODO: Use cookie to store session.
            # session.set_cookie('user_id', user.id)
            session['is_admin'] = user.is_admin()
            flash('You are now logged in.', 'success')
            return redirect(next_url or url_for('home.list_publish_articles'))
        else:
            flash('Incorrect email or password.', 'danger')
    return render_template('auth/login.html', next_url=next_url)


@auth_blueprint.route('/logout', methods=['POST'])
@login_required
def logout():
    session.clear()
    flash('You have been logged out', 'info')
    return redirect(url_for('home.list_publish_articles'))

project/blueprints/user_blueprint.py
from flask import Blueprint, request, flash, render_template

from project import db
from project.blueprints.auth_blueprint import only_anonymous, login_required, admin_required
from project.model.user import User

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/register', methods=['GET', 'POST'])
@only_anonymous
def register():
    if request.method == 'POST':
        # Get params
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password_confirm')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        # Check password
        if password != password_confirm:
            flash('Password does not match', 'danger')
            return render_template('user/register.html')
        # Checks integrity
        if User.find_one({'email': email, 'enabled': True}) is None:
            # Creates user
            user = User(email=email, first_name=first_name, last_name=last_name)
            user.hash_password(password)
            user.create()
            # Persists it
            db.session.commit()
        else:
            flash('The email is not available', 'danger')
    return render_template('user/register.html')


@user_blueprint.route('/retrieve-password', methods=['GET', 'POST'])
@only_anonymous
def retrieve_password():
    pass

@user_blueprint.route('/update-password', methods=['GET', 'POST'])
@login_required
def update_password():
    pass


@user_blueprint.route('/user', methods=['GET'])
@admin_required
def list_all():
    return render_template('user/management.html', users=User.find_all())


@user_blueprint.route('/user/<user_id>', methods=['DELETE'])
@admin_required
def delete(user_id):
    user = User.find_one({'id': user_id})
    user.soft_delete()
    db.session.commit()
    return '', 204


@user_blueprint.route('/user/<user_id>', methods=['PATCH'])
@admin_required
def restore(user_id):
    user = User.find_one({'id': user_id})
    user.restore()
    db.session.commit()
    return 200
  

project/templates/footer.html
<div class="footer">
    <span>Made with 💖 by luscofusco</span>
</div>

project/templates/header.html
<script>
function showDropdown() {
  document.getElementById("adminDropdown").classList.toggle("show");
}

window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
<div class="header">
    <!-- Logo -->
    <a href="/" ><image class="logo" src="/static/images/luscofusco_logotipo_B_Y.svg" alt="luscofusco logo"></image></a>
    
    <!-- Search bar -->
    <div class="search-bar">
        <form action="{{ url_for('article.search') }}">
          <input class="search-input" type="text" placeholder="Search.." name="q" />
          <button class="search-button link" type="submit">🔍</button>
        </form>
    </div>
  
    <!-- User actions -->
    <div class="user">
        {% if session.get('logged_in') %}
        <!-- Profile link -->
          <span>Hi! <a href="{{url_for('profile.details')}}">{{ session.get('user_name') }}</a>
          </span>
        
          <!-- Admin DropDown -->
          {% if session.get('is_admin') %}
              <div class="dropdown">
                  <button onclick="showDropdown()" class="dropbtn no-button link">Admin</button>
                  <div id="adminDropdown" class="dropdown-content">
                      <a href="{{url_for('article.list_all')}}">Articles</a>
                      <a href="{{url_for('user.list_all')}}">Users</a>
                  </div>
              </div>
          {% endif %}

        <!-- Logout -->
        <form class="logout" action="{{url_for('auth.logout')}}" method="post">
          <button class="no-button link" type="submit">Logout</button>
        </form>

        {% else %}
        <!-- Login -->
        <a href="{{url_for('auth.login')}}">Login</a>
        {% endif %}
    </div>
</div>

project/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <div class="home">
        {% include 'articles/list_published.html' %}
    </div>
{% endblock %}

project/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{{title}}</title>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='js/tags.js') }}"></script>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;700;900&family=Raleway:wght@200;400;500;700;900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    </head>
    <body>
        <!-- Header -->
        {% include 'header.html' %}

        <!-- Flash message -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class=flashes>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <!-- Content -->
        <div class="content">
            {% block content %}{% endblock %}
        </div>

        <!-- Footer -->
        {% include 'footer.html' %}
    </body>
</html>