project/blueprints/profile_blueprint.py
from flask import Blueprint, render_template, request, session, flash, url_for
from werkzeug.utils import redirect

from project import db
from project.blueprints.auth_blueprint import login_required
from project.model.user import User

profile_blueprint = Blueprint('profile', __name__)


@profile_blueprint.route('/profile', methods=['GET'])
@login_required
def details():
    return render_template('profile/details.html', current_user=User.find_one({'id': session.get('user_id')}))


@profile_blueprint.route('/profile/edit', methods=['GET', 'POST'])
@login_required
def update_details():
    current_user = User.find_one({'id': session.get('user_id')})
    if request.method == 'POST':
        email = request.form.get("email")
        first_name = request.form.get("first_name")
        last_name = request.form.get("last_name")
        if email == current_user.email or User.is_email_available(email):
            current_user.first_name = first_name
            current_user.last_name = last_name
            current_user.email = email
            current_user.update()
            session['user_name'] = first_name
            db.session.commit()
            return redirect(url_for('profile.details'))
        else:
            flash('Email is not available', 'error')
    return render_template('profile/edit.html', current_user=current_user)


@profile_blueprint.route('/profile/password', methods=['GET', 'POST'])
@login_required
def update_password():
    if request.method == 'POST':
        if request.form.get("password") == request.form.get("password_confirm"):
            current_user = User.find_one({'id': session.get('user_id')})
            current_user.hash_password(request.form.get("password"))
            current_user.update()
            db.session.commit()
            flash('Password updated', 'error')
            return redirect(url_for('profile.details'))
        else:
            flash('Password does not match', 'error')
            return redirect(url_for('profile.update_password'))
    return render_template('profile/edit_password.html')


@profile_blueprint.route('/profile', methods=['POST'])
@login_required
def delete():
    current_user = User.find_one({'id': session.get('user_id')})
    current_user.soft_delete()
    session.clear()
    db.session.commit()
    flash('Yout account has been delete', 'info')
    return redirect(url_for('home.list_publish_articles'))

project/templates/profile/details.html
{% extends 'layout.html' %}

{% block content %}
    <div class="cover"> 
        <image src="static/images/andrea_avatar.svg" alt="avatar"></image>
    </div>
    <section class="account">
        <h2>{{current_user.first_name}} {{current_user.last_name}}</h2>
        <h5>Email:</h5>
        <span>{{current_user.email}}</span>
        
        <section>
            <h5>You can...</h5>
                <div class="actions">
                    <a href="{{url_for('profile.update_password')}}" class="password">🔑 change password</a>
                    <a href="{{url_for('profile.update_details')}}" class="edit">✏️ Edit profile</a>
                    <form action="{{url_for('profile.delete')}}" method="post" class="delete">
                            <button type="submit" class="no-button link" >🗑️ Delete account</button>
                    </form>
                </div>
        </section>
    </section>
{% endblock %}

project/templates/profile/edit.html
{% extends 'layout.html' %}

{% block content %}

<div class="article-form">
    <h2>Edit your profile</h2>
    <form method="post">
        <!-- First name -->
        <div class="field">
            <label for="first_name">First name:</label>
            <input type="text" id="first_name" name="first_name" value="{{current_user.first_name}}"/>
        </div>

        <!-- Last name -->
        <div class="field">
            <label for="last_name">Last name:</label>
            <input type="text" id="last_name" name="last_name" value="{{current_user.last_name}}"/>
        </div>

        <!-- Email -->
        <div class="field">
            <label for="email">email:</label>
            <input type="text" id="email" name="email" value="{{current_user.email}}"/>
        </div>

        <!-- Button -->
        <button class="primary-button" type="submit" >update</button>
    </form>
</div>
{% endblock %}

project/templates/profile/edit_password.html
{% extends 'layout.html' %}

{% block content %}

<div class="article-form">
    <h2>Edit your password</h2>
    <form method="post">
        <!-- Password -->
        <div class="field">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" value=""/>
        </div>

        <!-- Password confirm -->
        <div class="field">
            <label for="password_confirm">Password (again):</label>
            <input type="password" id="password_confirm" name="password_confirm" value=""/>
        </div>

        <!-- Button -->
        <button class="primary-button" type="submit" >update</button>
    </form>
</div>
{% endblock %}