project/blueprints/articles_blueprint.py
from flask import Blueprint, request, render_template, url_for, session
from werkzeug.utils import redirect

from project import db
from project.blueprints.auth_blueprint import admin_required
from project.model.article import Article
from project.model.reaction import Reaction

article_blueprint = Blueprint('article', __name__)


@article_blueprint.route('/article/all', methods=['GET'])
@admin_required
def list_all():
    return render_template('articles/management.html', articles=Article.find_all())


@article_blueprint.route('/article/<article_id>', methods=['GET'])
def details(article_id):
    article = Article.find_one({'id': article_id})
    # Retrieve and aggregate reactions
    counter_reactions = article.get_reactions()
    # Find user reaction
    reaction = Reaction.find_one({'user_id': session.get('user_id'), 'article_id': article_id})
    user_reaction = reaction.emotion.name if reaction is not None else None
    # Pre-process article's tags
    tags = article.get_tags()
    return render_template('articles/details.html',
                           id=article_id,
                           title=article.title,
                           subtitle=article.subtitle,
                           body=article.body,
                           creation_date=article.creation_date,
                           reactions=counter_reactions,
                           user_reaction=user_reaction,
                           comments=article.comments,
                           tags=tags)


@article_blueprint.route('/article/<article_id>', methods=['DELETE'])
@admin_required
def delete(article_id):
    article = Article.find_one({'id': article_id})
    article.soft_delete()
    db.session.commit()
    return '', 204


@article_blueprint.route('/article/<article_id>/restore', methods=['PATCH'])
@admin_required
def restore(article_id):
    article = Article.find_one({'id': article_id})
    article.restore()
    db.session.commit()
    return '', 200


@article_blueprint.route('/article/<article_id>/edit', methods=['GET', 'POST'])
@admin_required
def edit(article_id):
    article = Article.find_one({'id': article_id})
    if request.method == 'GET':
        tags = article.get_attached_tags()
        return render_template('articles/form.html',
                               title=article.title,
                               article_title=article.title,
                               article_subtitle=article.subtitle,
                               article_body=article.body,
                               is_publish=article.is_publish,
                               header_form='edit article',
                               submit_button='edit',
                               tags=tags)
    elif request.method == 'POST':
        article.title = request.form.get("article_title")
        article.subtitle = request.form.get("article_subtitle")
        article.body = request.form.get("article_body")
        tags = request.form.get("tags")
        article.is_publish = True if request.form.get("article_publish") is not None else False
        article.update()
        article.attach_tags(tags)
        db.session.commit()
        return redirect(url_for('article.details', article_id=article.id))


@article_blueprint.route('/article', methods=['GET', 'POST'])
@admin_required
def create():
    if request.method == 'GET':
        return render_template('articles/form.html', title='create article', header_form='create article', submit_button='create')
    elif request.method == 'POST':
        title = request.form.get("article_title")
        subtitle = request.form.get("article_subtitle")
        body = request.form.get("article_body")
        tags = request.form.get("tags")
        is_publish = True if request.form.get("article_publish") is not None else False
        article = Article(title=title, subtitle=subtitle, body=body, is_publish=is_publish, writer=session.get('user_id'))
        article.create()
        article.attach_tags(tags)
        db.session.commit()
        return redirect(url_for('article.details', article_id=article.id))


@article_blueprint.route('/article/search', methods=['GET'])
def search():
    filters = dict()
    q = request.args.get('q')
    writer = request.args.get('writer')
    if q is not None:
        filters['q'] = q
    if writer is not None:
        filters['writer'] = writer
    filters['is_publish'] = True
    articles = Article.find_all(filters)
    return render_template('articles/search.html', filters=filters, articles=articles)

project/blueprints/comment_blueprint.py
from flask import Blueprint, request, session, url_for
from werkzeug.utils import redirect

from project import db
from project.blueprints.auth_blueprint import login_required
from project.model.article import Article
from project.model.comment import Comment

comment_blueprint = Blueprint('comment', __name__)


@comment_blueprint.route('/comment/<article_id>', methods=['POST'])
@login_required
def create(article_id):
    if Article.find_one({'id': article_id, 'is_publish': True, 'enabled': True}) is not None:
        Comment(article_id=article_id, user_id=session.get('user_id'), text=request.form.get('comment_text')).create()
        db.session.commit()
    return redirect(url_for('article.details', article_id=article_id))


@comment_blueprint.route('/comment/<comment_id>', methods=['DELETE'])
@login_required
def delete(comment_id):
    comment = Comment.find_one({'id': comment_id})
    if comment.user_id == session.get('user_id') or session.get('is_admin'):
        comment.soft_delete()
        db.session.commit()
        return '', 204
    else:
        return 401

project/blueprints/tag_blueprint.py
from flask import Blueprint, url_for, jsonify, render_template
from werkzeug.utils import redirect

from project.blueprints.auth_blueprint import login_required
from project.model.tag import Tag, TagSchema

tag_blueprint = Blueprint('tag', __name__)
tag_schema = TagSchema(many=True)


@tag_blueprint.route('/tag/<keyword>', methods=['GET'])
@login_required
def find_by_keyword(keyword):
    tags = Tag.find_all({'keyword': keyword})
    return jsonify(tag_schema.dump(tags)), 200


@tag_blueprint.route('/tag/<tag_id>/articles', methods=['GET'])
def related_articles(tag_id):
    tag = Tag.find_one({'id': tag_id})
    if tag is not None:
        # TODO: Improve next "query"
        articles = list(filter(lambda x: x.is_publish and x.enabled, map(lambda x: x.article, tag.articles)))
        return render_template('articles/search.html', filters={'tag': tag_id}, articles=articles)
    return 404

project/templates/articles/details.html
{% extends 'layout.html' %}

{% block content %}

<script>
// Article reaction
$(function() {
    $('a.emotion').bind('click', function() {
        $.ajax({
            url: $(location)[0].pathname.replace('article', 'reaction'),
            type: 'POST',
            data: JSON.stringify({ "emotion": $(this).attr('id') }),
            contentType: 'application/json; charset=utf-8',
            success: function(result) {
                location.reload();
            }
        });
    });
});

// Delete comment
$(function() {
    $('a.delete').bind('click', function() {
        $.ajax({
            url: '/comment/' + $(this).attr('id'),
            type: 'DELETE',
            success: function(result) {
                location.reload();
            }
        });
    });
});
</script>

<div class="article-info">
    <h1>{{title}}</h1>
    <h4>{{subtitle}}</h4>
    <div><span>{{creation_date.strftime('%d-%m-%Y')}}</span></div>
    <p class="article-body">{{body}}</p>

    <!-- Tags -->
    <div class="tags">
        {% for tag in tags %}
            <a class="tag" href="{{ url_for('tag.related_articles', tag_id=tag) }}">{{ tag }}</a>
        {% endfor %}
    </div>

    <!-- Emotions -->
    <div class="emotions">
        <a href="#" class="emotion idea {{ 'reaction' if user_reaction == 'IDEA' }}"
            id="idea">💡{{reactions.get('IDEA', 0)}}</a>
        <a href="#" class="emotion bug {{ 'reaction' if user_reaction == 'BUG' }}"
            id="bug">🐞{{reactions.get('BUG', 0)}}</a>
        <a href="#" class="emotion clap {{ 'reaction' if user_reaction == 'CLAP' }}"
            id="clap">👏{{reactions.get('CLAP', 0)}}</a>
        <a href="#" class="emotion love {{ 'reaction' if user_reaction == 'LOVE' }}"
            id="love">💕{{reactions.get('LOVE', 0)}}</a>
        <a href="#" class="emotion party {{ 'reaction' if user_reaction == 'PARTY' }}"
            id="party">🎉{{reactions.get('PARTY', 0)}}</a>
        <a href="#" class="emotion wizard {{ 'reaction' if user_reaction == 'WIZARD' }}"
            id="wizard">🧙{{reactions.get('WIZARD', 0)}}</a>
    </div>


    <section class="comments-section">
        <h4>Comments:</h4>
        <form action="{{url_for('comment.create', article_id=id)}}" method="post">
            <!-- Comment form -->
            <div class="field">
                <label for="comment_text">Give us your opinion:</label>
                <textarea type="text" id="comment_text" name="comment_text" rows="5"></textarea>
            </div>
            <!-- Button -->
            <button class="primary-button" type="submit">Comment!</button>
        </form>
        <!-- List all comments -->
        <div class="comments">
            {% for comment in comments %}
            <li>
                <div class="comment">
                    <div class="comment-actions">
                        {% if session.get('is_admin') or comment.user_id == session.get('user_id') %}
                        <a href="#" class="delete" id={{comment.id}}>🗑️</a>
                        {% endif %}
                    </div>
                    <p>{{comment.text}}</p>
                    <div class="comment-author">
                        <span>{{comment.commenter.first_name}}</span>
                        <span>{{comment.creation_date.strftime('%d-%m-%Y')}}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

project/templates/articles/form.html
{% extends 'layout.html' %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
var simplemde = new SimpleMDE({element: document.getElementById("article_body")});
</script>

<div class="article-form">
    <h2>{{header_form}}</h2>
    <form method="post">
        <input type="hidden" name="_method" value="patch" />
        <!-- title -->
        <div class="field">
            <label for="article_title">Article title:</label>
            <input type="text" id="article_title" name="article_title" value="{{article_title}}"/>
        </div>

        <!-- subtitle -->
        <div class="field">
            <label for="article_subtitle">Article Subtitle:</label>
            <input type="text" id="article_subtitle" name="article_subtitle" value="{{article_subtitle}}"/>
        </div>

        <!-- Body -->
        <div class="field">
            <label for="article_body">Article content:</label>
            <textarea type="text" id="article_body" name="article_body" rows="20">{{article_body}}</textarea>
        </div>

        <!-- Publish? -->
        
        <div class="is-published">
            <span>Publish article?</span>
            <div>
                <label class="checkbox path">
                    <input type="checkbox" id="article_publish" name="article_publish" {% if is_publish %}checked{% endif %}>
                    <svg viewBox="0 0 21 21">
                        <path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
                    </svg>
                </label>
            </div>
        </div>

        <!-- Tag Entry -->
        <div class="field">
            <label for="tags">Tags:</label>
            <!--<div id="master_div">
                    <div id="input_autocomplete">
                        <input id="tag-input" autocomplete="off" type="text" value="" class="form-control"/>
                    </div>
                    <div class="tags-categories" id="tags-categories"></div>
            </div>
            <input type="text" class="hidden" id="tags" name="tags" value="{{tags}}"/>-->
            <input type="text" id="tags" name="tags" value="{{tags}}"/>
        </div>

        <!-- Button -->
        <button class="primary-button" type="submit" >{{submit_button}}</button>
    </form>
</div>
{% endblock %}

project/templates/articles/info.html
{% extends 'layout.html' %}

{% block content %}

<script>
$(function() {
    $('a.emotion').bind('click', function() {
        $.ajax({
            url: $(location)[0].pathname.replace('article', 'reaction'),
            type: 'POST',
            data: JSON.stringify({ "emotion": $(this).attr('id') }),
            contentType: 'application/json; charset=utf-8',
            success: function(result) {
                location.reload();
            }
        });
    });
});
$(function() {
    $('a.delete').bind('click', function() {
        $.ajax({
            url: '/comment/' + $(this).attr('id'),
            type: 'DELETE',
            success: function(result) {
                location.reload();
            }
        });
    });
});
</script>

<div class="article-info">
    <h1 class="article-title">{{title}}</h1>
    <div><span>{{creation_date.strftime('%d-%m-%Y')}}</span></div>
    <p class="article-body">{{body}}</p>
    <div class="emotions">
        <a href="#" class="emotion idea {{ 'reaction' if user_reaction == 'IDEA' }}" id="idea">💡{{reactions.get('IDEA', 0)}}</a>
        <a href="#" class="emotion bug {{ 'reaction' if user_reaction == 'BUG' }}" id="bug">🐞{{reactions.get('BUG', 0)}}</a>
        <a href="#" class="emotion clap {{ 'reaction' if user_reaction == 'CLAP' }}" id="clap">👏{{reactions.get('CLAP', 0)}}</a>
        <a href="#" class="emotion love {{ 'reaction' if user_reaction == 'LOVE' }}" id="love">💕{{reactions.get('LOVE', 0)}}</a>
        <a href="#" class="emotion party {{ 'reaction' if user_reaction == 'PARTY' }}" id="party">🎉{{reactions.get('PARTY', 0)}}</a>
        <a href="#" class="emotion wizard {{ 'reaction' if user_reaction == 'WIZARD' }}" id="wizard">🧙{{reactions.get('WIZARD', 0)}}</a>
    </div>
    <div class="comments">
        <span>Comments:</span>
        <form action="{{url_for('comment.create', article_id=id)}}" method="post">
            <!-- Comment -->
            <div class="field">
                <label for="comment_text">give ud your opinion:</label>
                <textarea type="text" id="comment_text" name="comment_text"></textarea>
            </div>
            <!-- Button -->
            <button class="primary-button" type="submit" >Comment!</button>
        </form>
        <!-- List all comments -->
        {% for comment in comments %}
        <div class="comments">
            <li>
                <div class="comment">
                    <span>{{comment.text}}</span>
                    <span>{{comment.creation_date.strftime('%d-%m-%Y')}}</span>
                    <span>{{comment.commenter.first_name}}</span>
                    {% if session.get('is_admin') or comment.user_id == session.get('user_id') %}
                        <a href="#" class="delete" id={{comment.id}}>delete</a>
                    {% endif %}
                </div>
            </li>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

project/templates/articles/list.html
{% extends 'layout.html' %}

{% block content %}
    <script>
      $(function() {
        $('a.delete').bind('click', function() {
            $.ajax({
                url: '/article/' + $(this).attr('id'),
                type: 'DELETE',
                success: function(result) {
                    location.reload();
                }
            });
        });
      });
    </script>
    {% for article in articles %}
      <li>
          <a href="{{url_for('article.single_article', article_id=article.id)}}">{{ article.title }}</a>
          <a href="{{url_for('article.render_edit_article', article_id=article.id)}}">edit</a>
          <a href="#" class="delete" id={{article.id}}>delete</a>
      </li>
    {% endfor %}
    <a href="{{url_for('article.create_article')}}">create</a>
{% endblock %}

project/templates/articles/list_published.html
<section class="articles">
    <h2>Latest articles 🔥</h2>
    {% for article in articles %}
     <div class="article">
        <a class="article-title" href="{{url_for('article.details', article_id=article.id)}}"><h4>{{ article.title }}</h4></a>
         <p class="article-body">{{article.body | truncate(250)}}</p>
         <div class="reactions">
             <span class="number-reactions">{{article.get_number_of_reactions()}}</span>
             <span class="idea {{ 'hide' if not article.check_unique_reactions('IDEA') }}" id="idea">💡</span>
             <span class="bug {{ 'hide' if not article.check_unique_reactions('BUG') }}" id="bug">🐞</span>
             <span class="clap {{ 'hide' if not article.check_unique_reactions('CLAP') }}" id="clap">👏</span>
             <span class="love {{ 'hide' if not article.check_unique_reactions('LOVE') }}" id="love">💕</span>
             <span class="party {{ 'hide' if not article.check_unique_reactions('PARTY') }}" id="party">🎉</span>
             <span class="wizard {{ 'hide' if not article.check_unique_reactions('WIZARD') }}" id="wizard">🧙</span>
         </div>
     </div>
    {% endfor %}
</section>

project/templates/articles/management.html
{% extends 'layout.html' %}

{% block content %}
    <script>
      $(function() {
        $('a.delete').bind('click', function() {
            $.ajax({
                url: '/article/' + $(this).attr('id'),
                type: 'DELETE',
                success: function(result) {
                    location.reload();
                }
            });
        });
      });

      $(function() {
        $('a.restore').bind('click', function() {
            $.ajax({
                url: '/article/' + $(this).attr('id') + '/restore',
                type: 'PATCH',
                success: function(result) {
                    location.reload();
                }
            });
        });
      });
    </script>

    <section>
        <div>
            <a href="{{url_for('article.create')}}">➕ create</a>
        </div>
        <!-- Article table -->
        <table>
            <tr>
                <th>Article title</th>
                <th>Published?</th>
                <th>Actions</th>
            </tr>
            {% for article in articles %}
                <tr>
                    <td><a href="{{url_for('article.details', article_id=article.id)}}">{{ article.title }}</a></td>
                    <td><span>{{ article.enabled }}</span></td>
                    <td>
                        <a href="{{url_for('article.edit', article_id=article.id)}}">✏️</a>
                        {% if article.enabled %}
                            <a href="#" class="delete" id={{article.id}}>🗑️</a>
                        {% else %}
                            <a href="#" class="restore" id={{article.id}}>💱</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>
   
{% endblock %}

project/templates/articles/sample.html
 <div class="articles">
     <h2>Latest articles 🔥</h2>
    {% for article in articles %}
     <div class="article">
        <a class="article-title" href="{{url_for('article.single_article', article_id=article.id)}}">{{ article.title }}</a>
         <div class="article-body">
             {{article.body | truncate(250)}}
         </div>
         <div class="reactions">
             <span class="number-reactions">{{article.get_number_of_reactions()}}</span>
             <span class="idea {{ 'hide' if not article.check_unique_reactions('IDEA') }}" id="idea">💡</span>
             <span class="bug {{ 'hide' if not article.check_unique_reactions('BUG') }}" id="bug">🐞</span>
             <span class="clap {{ 'hide' if not article.check_unique_reactions('CLAP') }}" id="clap">👏</span>
             <span class="love {{ 'hide' if not article.check_unique_reactions('LOVE') }}" id="love">💕</span>
             <span class="party {{ 'hide' if not article.check_unique_reactions('PARTY') }}" id="party">🎉</span>
             <span class="wizard {{ 'hide' if not article.check_unique_reactions('WIZARD') }}" id="wizard">🧙</span>
         </div>
     </div>
    {% endfor %}
    <a href="{{url_for('article.create_article')}}">create</a>
 </div>

project/templates/articles/search.html
{% extends 'layout.html' %}

{% block content %}
<div class="articles">
     <h2>{{ articles | length }} results looking for:</h2>
     <ul>
         {% if 'q' in filters %}
            <h3><li>{{ filters.get('q') }}</li></h3>
         {% elif 'writer' in filters %}
            <h3><li>Author: {{ filters.get('writer') }}</li></h3>
         {% elif 'tag' in filters %}
            <h3><li>Tag: {{ filters.get('tag') }}</li></h3>
         {% endif %}
     </ul>
    {% for article in articles %}
         <div class="article">
            <a class="article-title" href="{{url_for('article.details', article_id=article.id)}}">{{ article.title }}</a>
             <div class="article-body">
                 {{ article.body | truncate(250) }}
             </div>
         </div>
    {% endfor %}
 </div>
{% endblock %}